#ASSIGNMENT 1

Problem Statement1: Write a Python program to multiply a M×N matrix by N×A matrix and create a real matrix product.

In [17]:
import numpy as np
M=int(input("Enter Value For M :"))
N=int(input("Enter Value For N :"))
A=int(input("Enter Value For A :"))
mat1=np.random.random((M,N))
mat2=np.random.random((N,A))
print("matrix 1 is\n",mat1,"\nmatrix 2 is\n",mat2)
print("\ndot product of matrix 1 and matrix 2 is\n",np.dot(mat1,mat2))

Enter Value For M :5
Enter Value For N :3
Enter Value For A :2
matrix 1 is
 [[0.38562412 0.06264529 0.34357218]
 [0.2728012  0.79893003 0.75605796]
 [0.06264856 0.98682889 0.38999105]
 [0.99569178 0.9081711  0.09568116]
 [0.90607139 0.10337032 0.77750743]] 
matrix 2 is
 [[0.93211523 0.89737442]
 [0.41597919 0.766165  ]
 [0.86622481 0.23168352]]

dot product of matrix 1 and matrix 2 is
 [[0.683116   0.47364586]
 [1.24153658 1.03208321]
 [0.80671589 0.90264747]
 [1.38876115 1.61148499]
 [1.56105908 1.07241967]]


Problem Statement2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.Hint:You can use isdigit(),islower(), and isupper() function.

In [19]:
arr1=list()
arr2=list()
arr3=list()
x =input("Original array :")
x=x.replace(" ",",")
arr=eval(x)
for i in arr:
  a=i.isdigit()
  arr1.append(a)
  b=i.islower()
  arr2.append(b)
  c=i.isupper()
  arr3.append(c)
print("Digits Only =",arr1)
print("Lower Cases Only =",arr2)
print("Upper Cases Only =",arr3)

Original array :['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits Only = [False, False, False, False, False, True]
Lower Cases Only = [False, False, False, False, True, False]
Upper Cases Only = [False, True, True, False, False, False]


Problem Statement3:Write a program that reads two space-separated positive integers X and Y as input and perform the following tasks:Tasks to be performed:
1.Create a list (lst1) starting at one (1) with 16 elements at a step of X 
2.Create a list (lst2) starting at one (1) with 16 elements at a step of Y 
3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4.Reshape both the NumPy arrays to (4,4)
5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
6.Print all the elements of np3 in a single dimension list like the 
format as shown below:a.[n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [24]:
X=int(input("Enter an integer for X :"))
Y=int(input("Enter an integer for Y :"))
lst1=list(np.arange(start=1,stop=X*16,step=X))
lst2=list(np.arange(start=1,stop=Y*16,step=Y))
np1=np.array(lst1)
np2=np.array(lst2)
np1.reshape(4,4)
np2.reshape(4,4)
np3=np1-np2
np3=np3.ravel()
print(np3)

Enter an integer for X :7
Enter an integer for Y :9
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


Problem Statement4: Write a Python program thattakes two integer-NumPy arrays, P and Q of shape [3∗3]and performthe following task:Task to be performed:Print the element-wise difference of the matrix P and Q(P−Q)

In [32]:
a=list()
b=list()
print("Enter elements for array 1:")
for i in range(0,9):
  a.append(int(input()))
print("Enter elements for array 2:")
for j in range(0,9):
  b.append(int(input()))
p=np.array(a)
q=np.array(b)
P=p.reshape(3,3)
Q=q.reshape(3,3)
print(P-Q)

Enter elements for array 1:
32
35
21
65
87
65
83
76
45
Enter elements for array 2:
21
23
56
34
43
24
42
41
14
[[ 11  12 -35]
 [ 31  44  41]
 [ 41  35  31]]
